# Generated by Django 2.2.9 on 2020-01-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20200120_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
